version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "photochatapp/android"
    update_schedule: "live"
    default_reviewers:
      - "tianhaoz95"
    default_labels:
      - "fastlane dependency update"
