name: frigga
on:
  push:
    paths: 
      - ".github/workflows/frigga.yml"
    branches: 
      - "master"
  release:
    types:
      - prereleased
jobs:
  promote-to-beta:
    name: promote to beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel stable
          flutter upgrade
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: install gem packages
        run: |
          cd photochatapp/android
          gem install bundler:1.17.3
          bundle install
          bundle exec fastlane install_plugins
          bundle exec fastlane update_plugins
      - name: build apk and app bundle package
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          ./scripts/setenv.sh
          cd ./photochatapp
          flutter pub get
          flutter test
          flutter build appbundle
      - name: upload app to Google Play Store
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          ./scripts/setenv.sh
          cd ./photochatapp/android
          bundle exec fastlane internal
          sleep 5
      - name: promote to beta
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          TRIGGER_EVENT: ${{ github.event_name }}
        run: |
          echo "triggering event type: $TRIGGER_EVENT"
          cd ./photochatapp/android
          bundle exec fastlane beta
