name: loki
on:
  release:	
    types:	
      - "published"	
      - "edited"
      - "prereleased"
  push:
    branches:
      - "master"
      - "actions/release_android__*"
    paths:
      - "photochatapp/pubspec.yaml"
      - "photochatapp/android/fastlane/Fastfile"
      - ".github/workflows/loki.yml"
      - "photochatapp/android/Gemfile"
      - "photochatapp/android/Gemfile.lock"
jobs:
  release-android:
    name: release android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check triggering event type
        env:
          TRIGGER_EVENT_NAME: ${{ github.event_name }}
          TRIGGER_EVENT: ${{ toJson(github.event) }}
          TRIGGER_EVENT_IS_PRERELEASE: ${{ github.event.prerelease }}
          TRIGGER_EVENT_IS_DRAFT: ${{ github.event.draft }}
        run: |
          echo "triggering event type: $TRIGGER_EVENT_NAME"
          echo "is prerelease: $TRIGGER_EVENT_IS_PRERELEASE"
          echo "is draft: $TRIGGER_EVENT_IS_DRAFT"
          echo "full event: $TRIGGER_EVENT"
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel stable
          flutter upgrade
      - name: install gem packages
        run: |
          cd photochatapp/android
          gem install bundler:1.17.3
          bundle install
          bundle exec fastlane install_plugins
          bundle exec fastlane update_plugins
      - name: build apk and app bundle package
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          ./scripts/setenv.sh
          cd ./photochatapp
          flutter pub get
          flutter test
          flutter build appbundle
      - name: upload app to Google Play Store
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          ./scripts/setenv.sh
          cd ./photochatapp/android
          bundle exec fastlane internal
          sleep 5
      - name: promote to alpha
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          TRIGGER_EVENT: ${{ github.event_name }}
        run: |
          cd ./photochatapp/android
          bundle exec fastlane alpha
      - name: promote to beta
        if: github.event_name == 'release' && github.event.release.prerelease == 'true'
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          cd ./photochatapp/android
          bundle exec fastlane beta
      - name: promote to production
        if: github.event_name == 'release' && github.event.release.prerelease == 'false'
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          cd ./photochatapp/android
          bundle exec fastlane production
